pipeline {
    agent {
        label 'php-agent'
    }
    
    stages {        
        stage('Install Dependencies') {
            steps {
                echo 'Preparing project...'
                dir('lab04/php-project') {
                    sh 'composer install --no-interaction --prefer-dist'
                }
            }
        }
        
        stage('Test') {
            steps {
                echo 'Running tests...'
                dir('lab04/php-project') {
                    sh 'php vendor/bin/phpunit'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed.'
        }
        success {
            echo 'All stages completed successfully!'
        }
        failure {
            echo 'Errors detected in the pipeline.'
        }
    }
}