---
- name: Install Docker on docker_hosts
  hosts: docker_hosts
  become: yes
  tasks:
    - name: Update apt package index
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - gnupg
          - lsb-release
        state: present

    - name: Add Docker GPG apt key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Update apt package index after adding repo
      apt:
        update_cache: yes

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Install Docker Compose plugin
      command: docker compose version
      register: compose_check
      ignore_errors: yes
      changed_when: false

    - name: Download and install Docker Compose if not present
      block:
        - name: Create directory for Docker plugins
          file:
            path: /usr/local/lib/docker/cli-plugins
            state: directory
            mode: '0755'

        - name: Download Docker Compose
          get_url:
            url: https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-linux-x86_64
            dest: /usr/local/lib/docker/cli-plugins/docker-compose
            mode: '0755'
      when: compose_check.rc != 0

    - name: Restart Docker service
      service:
        name: docker
        state: restarted